name: Docker Project Deploy

on:
  push:
    branches:
      - main

jobs:
  build_scan_backend:
    name: Сборка и сканирование бэкенда
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Сборка образа бэкенда
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: false
          load: true
          tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest

      - name: Запуск Trivy для бэкенда
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USER }}/docker-project-backend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build_scan_frontend:
    name: Сборка и сканирование фронтенда
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Сборка образа фронтенда
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: false
          load: true
          tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

      - name: Запуск Trivy для фронтенда
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USER }}/docker-project-frontend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

  run-with-docker-compose:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build via Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}